# -*- coding: utf-8 -*-
EMPLOYEE_TABLE = 0
POSITION_TABLE = 1
BRAND_TABLE = 2
SERVICE_TABLE = 3
CAR_TABLE = 4
CLIENT_TABLE = 5
RENT_TABLE = 6

MAIN_MENU_MODE = 0
PRINT_LIST_MENU_MODE = 1
FILL_LIST_MENU_MODE = 2
ADD_LIST_MENU_MODE = 3
DELETE_LIST_MENU_MODE = 4
REQUEST_HRD_LIST_MENU_MODE = 5
REQUEST_AUTOPARK_LIST_MENU_MODE = 6

MAIN_MENU_COUNT_NON_ACTIVATED = 4
MAIN_MENU_COUNT_ACTIVATED = 11
PRINT_LIST_MENU_COUNT = 7
FILL_LIST_MENU_COUNT = 7
ADD_LIST_MENU_COUNT = 7
DELETE_LIST_MENU_COUNT = 7
REQUEST_HRD_LIST_MENU_COUNT = 2
REQUEST_AUTOPARK_LIST_MENU_COUNT = 5